sudo: false
language: python
python: 3.8

branches:
 only:
   - master

install:
    - pip install -e .[test]

# Each step below must succeed for the build to pass
script:
    - coverage run --source=. test.py
    - coverage report -m
    - pycodestyle --format=pylint --max-line-length=120 --count .
